### PR TITLE
Capstone Project

### PR DESCRIPTION
**Pull request by Paul-Clue**
##  What I did in this project

- I created a home page that links to two other pages
- I created an about page 
- I created a page that shows a sample of how the company sells tickets
-
## Things to be aware of 
- My laptop broke down towards the end of the project.
- I switched computer. And as a result, somehow the histories of my main and work branch separated.
- I had to build a new repo with a main that has all the files of my work branch so that I could do a pull request.

## Languages I used to build this project
-HTML
- CSS

### CODE REVIEW

**Comment by Paul-Clue** [comment]
## Coding Issues:
Something is wrong with the webhint linters. I don't know what it is. I corrected all of the other linter errors. I tried to recopy the webhint linter file, but that still did not solve the issue. You can see the error message it is sending. I also tries to .gitignore the font folder, but still did not solve the issue. I do not know how to fix this webhint issue.

## Communcation Issue
I was looking at my email for the code review. No one told me that the review would be given in the Microverse portal. I accidentally found the review. I was going to right to student success about not receiving a review, but then I stumbled upon it. I should have been notified that the review would occur in the Microverse protal.

**Comment by Paul-Clue** [comment]
## Coding Issues:
Something is wrong with the webhint linters. I don't know what it is. I corrected all of the other linter errors. I tried to recopy the webhint linter file, but that still did not solve the issue. You can see the error message it is sending. I also tries to .gitignore the font folder, but still did not solve the issue. I do not know how to fix this webhint issue.

## Communication Issue:
I was looking at my email for the code review. No one told me that the review would be given in the Microverse portal. I accidentally found the review. I was going to write to student success about not receiving a review, but then I stumbled upon it. I should have been notified that the review would be given in the Microverse portal.

**Comment by voscarmv** [comment]
> ## Coding Issues:
> Something is wrong with the webhint linters. I don't know what it is. I corrected all of the other linter errors. I tried to recopy the webhint linter file, but that still did not solve the issue. You can see the error message it is sending. I also tries to .gitignore the font folder, but still did not solve the issue. I do not know how to fix this webhint issue.
> 
> ## Communication Issue:
> I was looking at my email for the code review. No one told me that the review would be given in the Microverse portal. I accidentally found the review. I was going to write to student success about not receiving a review, but then I stumbled upon it. I should have been notified that the review would be given in the Microverse portal.

Hi @Paul-Clue 

My name is Oscar, I'm the TSE currently re-reviewing your project.

As you can see, in the details about your Webhint errors, the error has nothing to do with the fonts folder. The errors are in the about and index pages:

image

With regards to not receiving an e-mail, feel free to contact student success about that issue. It might be a bug in the system.

As your project is currently not passing the Webhint tests, I won't be able to approve it in the current review, but please make any necessary corrections for your next code review request.

Best of luck!

**Comment by voscarmv** [comment]
@Paul-Clue if you need more details about the errors you must fix, check out this link: https://github.com/Paul-Clue/capstone2/pull/1/checks?check_run_id=1624161519

You may also click on the "Details" link, next to the failing tests in this Pull Request:

image

**Comment by Paul-Clue** [comment]
It seems that when I recopied the linter file that the bug was corrected. Thanks for pointing that out.

**Comment by voscarmv** [comment]
> It seems that when I recopied the linter file that the bug was corrected. Thanks for pointing that out.

You're welcome. Let me know if you need anything else.

**Comment by Paul-Clue** [comment]
This is to Oscar. The repo that I am submitting is the new repo. On the first repo that I made, I messed up the histories of the main branch and the project branch by not cloning the repo to my workstation properly. I then had to create this repo, which as you can see, has files and folders in the main branch. I had to push what I had on my workstation to this repo.

**Comment by voscarmv** [comment]
> This is to Oscar. The repo that I am submitting is the new repo. On the first repo that I made, I messed up the histories of the main branch and the project branch by not cloning the repo to my workstation properly. I then had to create this repo, which as you can see, has files and folders in the main branch. I had to push what I had on my workstation to this repo.

Got it. Thanks for the heads up.

**Comment by Paul-Clue** [comment]
Please review this review request. I have implemented all of the required changes that were detailed by each TSE. If I missed something let me know. I did most of the changes that were required.

**Comment by Paul-Clue** [comment]
## To Julio Anoveros
- If you read the README file, you will see that I did acknowledge the creator of the behance site. Her name is Cindy Shin.
- The README file is up to date.
- I don't know what "hero" section you are talking about, but all of the images are now fixed.
- The nav-bar is fixed all of the items are vertically aligned.
- The links on the home page,  about page, and ticket page all link to one another.
- I do not see the margin and border problems you are talking about. Can you be more clear?
- The _style_ of the nav-bar does match.
## To Raymond Omondi
- The use of Javascript is not required in this project. So making the menu in the mobile view interactive is not a requirement.
## To Mahmoud Mohammad Abbas
- You were the most helpful in this round of reviews.
- You made yourself clear about what needed to be fixed and I saw those mistakes. The mistakes you pointed out were actually there
- I like the fact that you offer your help, and you did not just criticize me for not knowing all of the specifications for HTML and CSS that exist on the entire internet.
- Thank you.
Please let me know if there are any more changes that need to be made.

**Comment by Paul-Clue** [comment]
## To Vicente Oscar Mier Vela
- I did all of the corrections you suggested. The only thing I could not do was to get the menu to toggle.
- I tried everything. But I could not get it to work. I  googled it a million times but could not find a way to fix it.
- If you can help, I would appreciate it.

**Comment by Paul-Clue** [comment]
Please pass this. I did everything you asked.

**Pull request merged**
